Repository BimalRajGyawali/hacktoberfest-java, pull requests merged in 2022-10, with the labels that each got.

#5 add Arrays.asList method of list creation
  src/main/java/org/example/collections/ListExample.java
Labels: hacktoberfest

#7 add Javalin in javaFrameworks list
  src/main/java/org/example/collections/ListExample.java
Labels: hacktoberfest-accepted

#9 update docs
  README.md
  src/main/java/org/example/CONTRIBUTING.md
Labels: hacktoberfest-accepted

#10 fix: moves CONTRIBUTING.md to root
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#13 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#14 add map.of presentation
  src/main/java/org/example/collections/MapExample.java
Labels: hacktoberfest, hacktoberfest-accepted

#22 Read from a text file line by line
  src/main/java/org/example/files/ReadLinebyLine.java
Labels: hacktoberfest-accepted

#24 Added a program to write a custom exception
  src/main/java/org/example/exceptions/CustomExceptionTest.java
Labels: hacktoberfest-accepted

#21 Fixed issue #15 (Writing to file)
  src/main/java/org/example/files/README.md
  src/main/java/org/example/files/WriteToFile.java
Labels: hacktoberfest-accepted

#23 Used Java 8 Files Api to read text file
  src/main/java/org/example/files/Files_api.java
Labels: hacktoberfest-accepted

#26 add file having example of class and object
  src/main/java/org/example/class and object/classex.java
Labels: hacktoberfest-accepted

#28 Class created and readme modified for oop
  src/main/java/org/example/oop/README.md
  src/main/java/org/example/oop/Student_Class.java
Labels: hacktoberfest-accepted

#27 Create Car.java
  src/main/java/org/example/class and object/Car.java
Labels: hacktoberfest-accepted

#31 Created Class and Object for Inheritance Concept
  src/main/java/org/example/inheritance/FlightApplication.java
Labels: hacktoberfest-accepted

#30 Enhanced README.md
  README.md
Labels: hacktoberfest-accepted

#29 feat: add reflection demo to the repo
  src/main/java/org/example/reflection/README.md
  src/main/java/org/example/reflection/ReflectionDemo.java
  src/main/java/org/example/reflection/Student.java
Labels: hacktoberfest-accepted

#32 Copying file with the help of file handling
  src/main/java/org/example/exceptions/ArrayIndexOutOfBound.java
  src/main/java/org/example/exceptions/DivideByZeroException.java
  src/main/java/org/example/files/CopyFileWithBuffer.java
  src/main/java/org/example/files/CopyFileWithoutBuffer.java
Labels: hacktoberfest-accepted

#34 added a program for class object demonstration
  src/main/java/org/example/class and object/Phone.java
Labels: hacktoberfest-accepted

#33 Simple Login Logic program using Java
  src/main/java/org/example/oop/SimpleLogin.java
Labels: hacktoberfest-accepted

#36 Employee and Manager program created using concept of inheritance
  src/main/java/org/example/inheritance/EmployeeAndManager.java
Labels: hacktoberfest-accepted

#37 java static keyword
  src/main/java/org/example/static/JavaStaticKeyword.java
Labels: hacktoberfest-accepted

#38 Serialize and Deserialize implemented using concept of file handling
  src/main/java/org/example/files/SerializationAndDeserialization.java
Labels: hacktoberfest-accepted

#39 Nabin contribution
  src/main/java/org/example/lambda/LambdaDemo.java
  src/main/java/org/example/lambda/Performer.java
  src/main/java/org/example/lambda/Printable.java
  src/main/java/org/example/lambda/README.md
  src/main/java/org/example/lambda/Summable.java
Labels: hacktoberfest-accepted

#35 Parvez created CompileTime and RunTime Polymorphism
  src/main/java/org/example/Polymorphism/CompileTimePolymorphism.java
  src/main/java/org/example/Polymorphism/RunTimePolymorphism.java
Labels: hacktoberfest-accepted

#41 Example of Bounded Generic methods created, with a sample Dog and Cat…
  src/main/java/org/example/generics/BoundedGenerics.java
Labels: hacktoberfest-accepted

#43 added bst programs
  src/main/java/org/example/BinarySearchTree/ModifyTree.java
  src/main/java/org/example/BinarySearchTree/PrintBetweenRange.java
  src/main/java/org/example/BinarySearchTree/deletion.java
  src/main/java/org/example/BinarySearchTree/implementation.java
Labels: hacktoberfest-accepted

#44 Added a Stack example in Java
  src/main/java/org/example/collections/StackExample.java
Labels: hacktoberfest-accepted

#45 Added program for interface demonstration
  src/main/java/org/example/inheritance/TestInterface2.java
Labels: hacktoberfest-accepted

#46 enhanced README.md
  README.md
Labels: hacktoberfest-accepted

#47 Adding a java program to find if a given number is Keith Number or Not
  src/main/java/org/example/keith number in java/README.md
  src/main/java/org/example/keith number in java/keith.java
Labels: hacktoberfest-accepted

#48 example of enums
  src/main/java/org/example/Enums/Day.java
  src/main/java/org/example/Enums/README.md
  src/main/java/org/example/Enums/Schedule.java
  src/main/java/org/example/Enums/SchedulingApp.java
Labels: hacktoberfest-accepted

#49 Added Array creation and declaration
  src/main/java/org/example/Arrays/README.md
  src/main/java/org/example/Arrays/array.java
Labels: hacktoberfest-accepted

#50 Factory Design Pattern
  EmailNotification.java
  Notification.java
  NotificationFactory.java
  PushNotification.java
  SMSNotification.java
  Test.java
Labels: hacktoberfest-accepted

#51 Encapsulation concept added to the oop package
  src/main/java/org/example/oop/Encapsulation.java
Labels: hacktoberfest-accepted

#52 array example
  src/main/java/org/example/Arrays/LongestName.java
Labels: hacktoberfest-accepted

#53 added a program to get largest number from an array
  src/main/java/org/example/Arrays/LargestNumOfAnArray.java
  src/main/java/org/example/Strings/ReversedString.java
  src/main/java/org/example/exceptions/NullPointException.java
Labels: hacktoberfest-accepted

#54 pattern java by simple trick
  src/main/java/org/example/CodePractices/Pattern.java
Labels: hacktoberfest-accepted

#57 Added implementation of interface
  src/main/interface/interface.java
Labels: hacktoberfest-accepted

#58 Added some basic java codes
  src/main/java/org/example/Basic codes/AddNaturalNumbersWithoutLoop.java
  src/main/java/org/example/Basic codes/ArmstrongNumber.java
  src/main/java/org/example/Basic codes/ArrayDemo.java
  src/main/java/org/example/Basic codes/DecimalToBinary.java
  src/main/java/org/example/Basic codes/EvenOdd.java
  src/main/java/org/example/Basic codes/EvenUsingFor.java
  src/main/java/org/example/Basic codes/FibonacciSeries.java
  src/main/java/org/example/Basic codes/LeapYear.java
  src/main/java/org/example/Basic codes/MatrixAddition.java
  src/main/java/org/example/Basic codes/MaxAmongThree.java
  src/main/java/org/example/Basic codes/Methoddemo.java
  src/main/java/org/example/Basic codes/Minmax.java
  src/main/java/org/example/Basic codes/Palindrome.java
  src/main/java/org/example/Basic codes/PrimeNumbers.java
  src/main/java/org/example/Basic codes/PrintAlphabets.java
  src/main/java/org/example/Basic codes/PrintHelloWorld.java
  src/main/java/org/example/Basic codes/PrintName.java
  src/main/java/org/example/Basic codes/Raisedto.java
  src/main/java/org/example/Basic codes/ReverseDigits.java
  src/main/java/org/example/Basic codes/Series.java
  src/main/java/org/example/Basic codes/SignCount.java
  src/main/java/org/example/Basic codes/SumOfArray.java
  src/main/java/org/example/Basic codes/SumOfEveninArray.java
  src/main/java/org/example/Basic codes/SwapNumbers.java
  src/main/java/org/example/Basic codes/Tables.java
  src/main/java/org/example/Basic codes/TwoDimensionalArray.java
  src/main/java/org/example/Basic codes/UpperCase.java
  src/main/java/org/example/Basic codes/ValidVotingAge.java
  src/main/java/org/example/Basic codes/VariablesDemo.java
Labels: hacktoberfest-accepted

#60 Inheritance Example
  src/main/java/org/example/inheritance/InheritanceExample.java
  src/main/java/org/example/inheritance/InheritanceInInterfaces.java
  src/main/java/org/example/oop/InheritanceExample.java
Labels: hacktoberfest-accepted

#61 Added LinkedList using java
  src/main/java/org/example/LinkedList/LinkedList.java
  src/main/java/org/example/LinkedList/Node.java
  src/main/java/org/example/LinkedList/Runner.java
Labels: hacktoberfest-accepted

#63 Example code for Java Stream Class
  src/main/java/org/example/streams/Readme.md
  src/main/java/org/example/streams/StreamExample.java
  src/main/java/org/example/streams/model/Employee.java
Labels: hacktoberfest-accepted

#64 java palindrome finder
  src/main/java/org/example/CodePractices/Palindrome.java
Labels: hacktoberfest-accepted

#66 New Changes
  src/main/java/org/example/Interfaces/ReptileInterface.java
Labels: hacktoberfest-accepted

#69 Create OccurenceOfCharInString.java
  src/main/java/org/example/CodePractices/OccurenceOfCharInString.java
Labels: hacktoberfest-accepted

#72 Added LinkedList Implementation
  .gitignore
  LinkedList_Java/DetectingLoops.java
  LinkedList_Java/LinkedList.java
  LinkedList_Java/LinkedListCollection.java
  LinkedList_Java/PalindromeLinkedList.java
  LinkedList_Java/QueueLinkedList.java
  LinkedList_Java/RemoveNthNodeFromEnd.java
  LinkedList_Java/ReverseLinkedList.java
  LinkedList_Java/StackLinkedList.java
Labels: hacktoberfest-accepted

#73 Added Basic Java Codes
  Basic/AddBinary.java
  Basic/Armstrong.java
  Basic/ArrayCheckSort.java
  Basic/ArrayMinMax.java
  Basic/Calculator.java
  Basic/ClearBit.java
  Basic/DtoB.java
  Basic/Election.java
  Basic/GCD.java
  Basic/GetBit.java
  Basic/GuessNumber.java
  Basic/LinearSearch.java
  Basic/Palindrome.java
  Basic/Pascal.java
  Basic/PatternDiamond.java
  Basic/PatternPalinPyramid.java
  Basic/PatternPyramid.java
  Basic/PatternRhombus.java
  Basic/PosiNegaZero.java
  Basic/PowerOfTwo.java
  Basic/Reversesb.java
  Basic/SpiralMatrix.java
  Basic/Transpose.java
  Basic/TwoDArray.java
  Basic/TwoDArraySearch.java
  Basic/UpdateBit.java
Labels: hacktoberfest-accepted

#74 QuizCheckResult
  DudeneyNumber.java
  QuizCheckResult.java
Labels: hacktoberfest-accepted

#76 Added Sorting Algorithms
  Sorting/BubbleSort.java
  Sorting/InsertionSort.java
  Sorting/MergeSort.java
  Sorting/QuickSort.java
  Sorting/SelectionSort.java
Labels: hacktoberfest-accepted

#71 Added Dijkstras Algorithm
  src/main/java/org/example/Algorithms/DijkstraClass.java
  src/main/java/org/example/Algorithms/FloydsClass.java
Labels: hacktoberfest-accepted

#79 update BubbleSort.java
  Sorting/BubbleSort.java
Labels: hacktoberfest-accepted

#81 Create radixSort.java
  Sorting/radixSort.java
Labels: hacktoberfest-accepted

#82 Added New Patterns
  Patterns/Butterfly.java
  Patterns/Diamond.java
  Patterns/FloydsTriangle.java
  Patterns/HalfPyramid.java
  Patterns/HollowRectangle.java
  Patterns/InvertedHalfPyramid.java
  Patterns/NumberPyramid.java
  Patterns/Palindromic.java
  Patterns/RotatedHalfPyramid.java
  Patterns/SolidRectangle.java
  Patterns/ZeroOneTriangle.java
Labels: hacktoberfest-accepted

#84 Create Binary Search in Java
  Basic/BinarySearch.java
Labels: hacktoberfest-accepted

#90 refactor: moves BinarySearch to algorithms package
  src/main/java/org/example/algorithms/searching/BinarySearch.java
Labels: hacktoberfest-accepted

#92 refactor: removes Basic folder
  Basic/BinarySearch.java
Labels: hacktoberfest-accepted

#93 Added function codes
  src/main/java/org/example/oop/functions/Circumference.java
  src/main/java/org/example/oop/functions/Even.java
  src/main/java/org/example/oop/functions/Factorial.java
  src/main/java/org/example/oop/functions/Prime.java
  src/main/java/org/example/oop/functions/Table.java
  src/main/java/org/example/oop/functions/Vote.java
Labels: hacktoberfest-accepted

#99 new Kadden's Algorithm in algorithms folder
  src/main/java/org/example/algorithms/KaddensAlgo.java
Labels: hacktoberfest-accepted

#103 Implementation of Queue Data Structure using Array
  src/main/java/org/example/datastructures/queue/ImplementationOfQueueUsingArray.java
Labels: hacktoberfest-accepted

#107 Nn
  src/main/java/org/example/oop/abstraction/CarModel.java
  src/main/java/org/example/oop/classandobject/Students.java
  src/main/java/org/example/oop/encapsulation/Areas.java
  src/main/java/org/example/oop/inheritance/Teachers.java
  src/main/java/org/example/oop/polymorphism/SumPoly.java
Labels: hacktoberfest-accepted

#83 Added Stack and Queue folder
  src/main/java/org/example/datastructures/queue/CircularQueue.java
  src/main/java/org/example/datastructures/queue/DequeDemo.java
  src/main/java/org/example/datastructures/queue/Node.java
  src/main/java/org/example/datastructures/queue/QueueUsing2Stack.java
  src/main/java/org/example/datastructures/queue/QueueUsingArray.java
  src/main/java/org/example/datastructures/queue/QueueUsingLL.java
  src/main/java/org/example/datastructures/queue/deque.java
  src/main/java/org/example/datastructures/stack/InfixToPostifx.java
  src/main/java/org/example/datastructures/stack/InfixToPrefix.java
  src/main/java/org/example/datastructures/stack/StackArrayList.java
  src/main/java/org/example/datastructures/stack/StackPushBottom.java
  src/main/java/org/example/datastructures/stack/StackUsingArray.java
  src/main/java/org/example/datastructures/stack/StackUsingLL.java
Labels: hacktoberfest-accepted

#109 Implementation of Stack using Arraylist
  src/main/java/org/example/datastructures/stack/ImplementationOfStackUsingArraylist.java
Labels: hacktoberfest-accepted

#110 Added Longest Palindromic Substring
  src/main/java/org/example/algorithms/LongestPalindromicSubString.java
Labels: hacktoberfest-accepted

#111 It will Display The Sum of N Numbers of Fibonacci Series
  src/main/java/org/example/algorithms/FibonacciSeries.java
Labels: hacktoberfest-accepted

#85 Java Programs #55 issue Solved
  CheckAlphabetOrNot.java
  CkeckPrime.java
  ConvertCharToAscii.java
  FindGCD.java
  FindLcm.java
  FindQuotient.java
  GreatestNumber.java
  LeapYear.java
  MatrixMultiplication.java
  NumReverse.java
  PrintAlphabet.java
  PrintArrayUserInput.java
  PrintPrimeNum1ToN.java
  arrayofobj.java
  cmdline.java
  hierarchical.java
Labels: hacktoberfest-accepted

#98 added queue and stack implementation in java
  src/main/java/org/example/datastructures/queue/ArrayQueue.java
  src/main/java/org/example/datastructures/queue/LinkedQueue.java
  src/main/java/org/example/datastructures/queue/Queue.java
  src/main/java/org/example/datastructures/stack/ArrayStack.java
  src/main/java/org/example/datastructures/stack/LinkedStack.java
  src/main/java/org/example/datastructures/stack/RPN.java
  src/main/java/org/example/datastructures/stack/Stack.java
Labels: hacktoberfest-accepted

#106 Remove Duplicates a basic problem of java
  src/main/java/org/example/basics/RemoveDuplicate.java
Labels: hacktoberfest-accepted

#102 Checking that the Given Array Is Sorted or Not using Recurssion.
  src/main/java/org/example/algorithms/CheckArraySortedNot.java
Labels: hacktoberfest-accepted

#115 added linear_search.java
  src/main/java/org/example/algorithms/searching/LinearSearch.java
Labels: hacktoberfest-accepted

#117 Added Recursion
  src/main/java/org/example/algorithms/recursion/CalcPower.java
  src/main/java/org/example/algorithms/recursion/Fabonacci.java
  src/main/java/org/example/algorithms/recursion/FindOccurance.java
  src/main/java/org/example/algorithms/recursion/Reverse.java
  src/main/java/org/example/algorithms/recursion/TowerOfHanoi.java
Labels: hacktoberfest-accepted

#122 Create PreorderBinaryTree.java
  src/main/java/org/example/datastructures/binarytree/PreorderBinaryTree.java
Labels: hacktoberfest-accepted

#124 Create Permutation.java
  src/main/java/org/example/basics/Permutation.java
Labels: hacktoberfest-accepted

#105 Create FactorialNNumber.java
  src/main/java/org/example/algorithms/FactorialNNumber.java
Labels: hacktoberfest-accepted

#126 Print The Character Pattern
  src/main/java/org/example/patterns/CharacterPattern.java
Labels: hacktoberfest-accepted

#129 Polymorphism example
  src/main/java/org/example/oop/polymorphism/Overriding.java
Labels: hacktoberfest-accepted

#119 Finding out an pivot element of sum of element in array
  src/main/java/org/example/datastructures/arrays/FindingPivotSumElement.java
Labels: hacktoberfest-accepted

#136 Added Examples for Functional Programming.
  src/main/java/org/example/functionalprogramming/ConsumerExample.java
  src/main/java/org/example/functionalprogramming/FunctionExample.java
  src/main/java/org/example/functionalprogramming/PredicateExample.java
  src/main/java/org/example/functionalprogramming/SupplierExample.java
Labels: hacktoberfest-accepted

#137 Added number crunching programs
  src/main/java/org/example/numbercrunching/CircularPrime.java
  src/main/java/org/example/numbercrunching/CompositeMagic.java
  src/main/java/org/example/numbercrunching/GoldBach.java
  src/main/java/org/example/numbercrunching/ISBNCode.java
  src/main/java/org/example/numbercrunching/PrimePalindrome.java
Labels: hacktoberfest-accepted

#140 added recursive bubble sorting algorithm
  src/main/java/org/example/algorithms/sorting/RecursiveBubbleSort.java
Labels: hacktoberfest-accepted

#143 Calculator_Using_Applet_awt
  src/main/java/org/example/awt/CalculatorUsingAppletawt.java
Labels: hacktoberfest-accepted

#144 Cyclic Sort Added
  src/main/java/org/example/algorithms/sorting/CyclicSort.java
Labels: hacktoberfest-accepted

#138 reversing an array using temp variable
  src/main/java/org/example/basics/ReverseArray.java
  src/main/java/org/example/datastructures/stack/InfixToPostfix.java
Labels: hacktoberfest-accepted

#153 Added Prim's Algorithm
  src/main/java/org/example/algorithms/PrimsAlgorithm.java
Labels: hacktoberfest-accepted

#156 Created DFS.java
  src/main/java/org/example/algorithms/DFS.java
Labels: hacktoberfest-accepted

#154 Amazon questions - element and frequency count in array
  src/main/java/org/example/basics/CodeForFinal.java
  src/main/java/org/example/basics/CodeForThis.java
  src/main/java/org/example/basics/DublicateArrayCount.java
Labels: hacktoberfest-accepted

#158 added code for this keyword
  src/main/java/org/example/oop/thiskeyword/JavaThisKeyword.java
Labels: hacktoberfest-accepted

#159 Added HeapSort.java
  src/main/java/org/example/algorithms/sorting/HeapSort.java
Labels: hacktoberfest-accepted

#163 Create TrafficLight.java
  src/main/java/org/example/awt/TrafficLight.java
Labels: hacktoberfest-accepted

#165 Create InorderBinaryTree.java
  src/main/java/org/example/datastructures/binarytree/InorderBinaryTree.java
Labels: hacktoberfest-accepted

#167 NumberRectangle a pattern that prints rectangle with number
  src/main/java/org/example/patterns/NumberRectangle.java
Labels: hacktoberfest-accepted

#171 Level order traversal of Binary Tree
  src/main/java/org/example/datastructures/binarytree/LevelorderBinaryTree.java
Labels: hacktoberfest-accepted

#172 NQueen problem using backtracking in java
  src/main/java/org/example/algorithms/backtracking/NQueen.java
Labels: hacktoberfest-accepted

#174 docs: adds naming conventions
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#183 Sudoku code using backtracking
  src/main/java/org/example/algorithms/backtracking/Sudoku.java
Labels: hacktoberfest-accepted

#184 Tiles Problem using backtracking
  src/main/java/org/example/algorithms/backtracking/TilesProblem.java
Labels: hacktoberfest-accepted

#191 Added sort linkedlist and add two linkedlist programs- updated
  src/main/java/org/example/datastructures/linkedlist/algo/AddTwoLinkedLists.java
  src/main/java/org/example/datastructures/linkedlist/algo/SortLinkedList.java
Labels: hacktoberfest-accepted

#196 adding rat in a maze backtracking problem
  src/main/java/org/example/algorithms/backtracking/RatInMaze.java
Labels: hacktoberfest-accepted

#198 Shell Sort Added
  src/main/java/org/example/algorithms/sorting/SheelSort.java
Labels: hacktoberfest-accepted

#199 TarjanAlgorithm.java
  src/main/java/org/example/algorithms/TarjanAlgorithm.java
Labels: hacktoberfest-accepted

#201 Field modification through reflection
  src/main/java/org/example/algorithms/backtracking/RatInMaze.java
  src/main/java/org/example/reflection/BestFruit.java
  src/main/java/org/example/reflection/FieldModificationDemo.java
  src/main/java/org/example/reflection/README.md
  src/main/java/org/example/reflection/ReflectionDemo.java
Labels: hacktoberfest-accepted

#202 Simple threads
  src/main/java/org/example/threads/README.md
  src/main/java/org/example/threads/Threads.java
Labels: hacktoberfest-accepted

#203 Added Kruskals Algo
  src/main/java/org/example/algorithms/Kruskal.java
Labels: hacktoberfest-accepted

#206 Added Deflate examples
  src/main/java/org/example/algorithms/Kruskal.java
  src/main/java/org/example/algorithms/TarjanAlgorithm.java
  src/main/java/org/example/deflate/DeflateDemo.java
  src/main/java/org/example/deflate/README.md
Labels: hacktoberfest-accepted

#208 Tree conversion
  src/main/java/org/example/algorithms/treestore/README.md
  src/main/java/org/example/algorithms/treestore/TreeStore.java
Labels: hacktoberfest-accepted

#214 Added Complex calculations
  src/main/java/org/example/basics/Complex.java
Labels: hacktoberfest-accepted

#216 Initial commit
  src/main/java/org/example/algorithms/SpiralMatrix.java
Labels: hacktoberfest-accepted

#223 Example of New String Features introduced in Java 11
  src/main/java/org/example/strings/Readme.md
  src/main/java/org/example/strings/StringBlankCheckExample.java
  src/main/java/org/example/strings/StringPrintLines.java
  src/main/java/org/example/strings/StringRepeatExample.java
  src/main/java/org/example/strings/StringStripExample.java
Labels: hacktoberfest-accepted

#225 Code for removing duplicates from sorted linked list
  src/main/java/org/example/datastructures/linkedlist/algo/RemoveDuplicateNodesFromSortedList.java
Labels: hacktoberfest-accepted

#226 added a recursive algorithm
  src/main/java/org/example/algorithms/recursion/KthGrammar.java
Labels: hacktoberfest-accepted

#227 feat. adds Run-Length Encoding
  src/main/java/org/example/compressiontechniques/CompressionApp.java
  src/main/java/org/example/compressiontechniques/README.md
  src/main/java/org/example/compressiontechniques/RunLengthEncoder.java
Labels: hacktoberfest-accepted

#234 Height of binary tree
  src/main/java/org/example/datastructures/binarytree/HeightOfBinaryTree.java
Labels: hacktoberfest-accepted

#235 Right Side view of binary tree
  src/main/java/org/example/datastructures/binarytree/RightSideViewOfBinaryTree.java
Labels: hacktoberfest-accepted

#236 Left side view of binary tree
  src/main/java/org/example/datastructures/binarytree/LeftSideViewOfBinaryTree.java
Labels: hacktoberfest-accepted

#241 Example code for new features introduced in Java 14 for switch expression
  src/main/java/org/example/switchexpression/Readme.md
  src/main/java/org/example/switchexpression/SwitchExample.java
Labels: hacktoberfest-accepted

#244 Count number of nodes in binary tree
  src/main/java/org/example/datastructures/binarytree/CountNodesOfBinaryTree.java
Labels: hacktoberfest-accepted

#247 String is Palindrome or not
  src/main/java/org/example/strings/PalindromeString.java
Labels: hacktoberfest-accepted

#248 Valid Anagram String
  src/main/java/org/example/strings/ValidAnagramString.java
Labels: hacktoberfest-accepted

#257 Made changes in Sudoku.java
  src/main/java/org/example/leetcode/Sudoku.java
Labels: hacktoberfest-accepted

#263 I update String Intern Example
  src/main/java/org/example/strings/StringInternExample.java
Labels: hacktoberfest-accepted

#264 update String Trim Example
  src/main/java/org/example/strings/StringTrimExample.java
Labels: hacktoberfest-accepted

#266 update String Lower Case Example
  src/main/java/org/example/strings/StringLowerCaseExample.java
Labels: hacktoberfest-accepted

#267 update String Upper Case Example
  src/main/java/org/example/strings/StringUpperCaseExample.java
Labels: hacktoberfest-accepted

#268 update String Length Example
  src/main/java/org/example/strings/StringLengthExample.java
Labels: hacktoberfest-accepted

#269 update Odd Even Using Bit Manipulation
  src/main/java/org/example/bitmanipulation/OddEvenUsingBitManipulation.java
Labels: hacktoberfest-accepted

#271 Added ValidPangram.java
  src/main/java/org/example/basics/ValidPangram.java
Labels: hacktoberfest-accepted

#274 Substring of a String
  src/main/java/org/example/strings/SubstringExample.java
Labels: hacktoberfest-accepted

#275 String Reverse in String
  src/main/java/org/example/strings/StringReverse.java
Labels: hacktoberfest-accepted

#276 Checking Size using Switch
  src/main/java/org/example/switchexpression/SizeChecker.java
Labels: hacktoberfest-accepted

#280 minimum sum using greedy
  src/main/java/org/example/leetcode/MinimumSumGreedy.java
Labels: hacktoberfest-accepted

#279 Comparing Two Strings ignoring case
  src/main/java/org/example/strings/StringEqualsIgnoreCase.java
Labels: hacktoberfest-accepted

#278 Replacing Character in a String
  src/main/java/org/example/strings/CharReplaceInString.java
Labels: hacktoberfest-accepted

#270 Concatenating two strings using java
  src/main/java/org/example/strings/StringConcat.java
Labels: hacktoberfest-accepted

#283 Add only celciustofarenheit method
  src/main/java/org/example/algorithms/CelciusToFarenheitMethod.java
Labels: hacktoberfest-accepted

#286 string replace example
  src/main/java/org/example/strings/StringReplaceExample.java
Labels: hacktoberfest-accepted

#289 Create ReversedPyramidStarPattern.java
  src/main/java/org/example/patterns/Descendingorder.java
  src/main/java/org/example/patterns/ReversedPyramidStarPattern.java
Labels: hacktoberfest-accepted

#292 Use Of Bitwise OR in bit manipulation
  src/main/java/org/example/bitmanipulation/UseOfBitwiseOR.java
Labels: hacktoberfest-accepted

#294 Counting Total SetBits in an Integer
  src/main/java/org/example/bitmanipulation/CountTotalSetBits.java
Labels: hacktoberfest-accepted

#295 Finding Missing Number in an Array using Xor
  src/main/java/org/example/bitmanipulation/MissingNumberUsingXor.java
Labels: hacktoberfest-accepted

#296 Sum of Diagonal Matrix
  src/main/java/org/example/leetcode/DiagonalMatrixSum.java
Labels: hacktoberfest-accepted

#298 Create UseOfLeftShiftOperator.java
  src/main/java/org/example/bitmanipulation/UseOfLeftShiftOperator.java
Labels: hacktoberfest-accepted

#300 Example of collection ArrayList
  src/main/java/org/example/collections/ArrayListExample.java
Labels: hacktoberfest-accepted

#302 Added package info
  src/main/java/org/example/basics/MatrixReversal.java
Labels: hacktoberfest-accepted

#301 Example of vector collection
  src/main/java/org/example/collections/VectorExample.java
Labels: hacktoberfest-accepted

#303 Example of Priority Queue collection
  src/main/java/org/example/collections/PriorityQueueExample.java
Labels: hacktoberfest-accepted

#304 Example of HashSet collection
  src/main/java/org/example/collections/HashSetExample.java
Labels: hacktoberfest-accepted

#305 added ValidAnagram.java(leetcode 242)
  src/main/java/org/example/leetcode/ValidAnagram.java
Labels: hacktoberfest-accepted

#306 Use of Right Shift Operator
  src/main/java/org/example/bitmanipulation/UseOfRightShiftOperator.java
Labels: hacktoberfest-accepted

#307 Use Of Bitwise Complement
  src/main/java/org/example/bitmanipulation/UseOfBitwiseComplement.java
Labels: hacktoberfest-accepted

#308 Josephus Problem Using Recursion
  src/main/java/org/example/algorithms/recursion/JosephusUsingRecursion.java
Labels: hacktoberfest-accepted

#309 Reverse Levelorder Binary Tree
  src/main/java/org/example/datastructures/binarytree/ReverseLevelorderBinaryTree.java
Labels: hacktoberfest-accepted
